### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by forgetso** [b-mueller/mythril#16]
Hi, the package doesn't properly install for me. Any ideas?

```
Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/81/2r7bsh810jd7yrt90z9x1xgh0000gn/T/pip-build-1s_rFU/mythril/setup.py", line 163, in <module>
      scripts=['mythril']
    File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 257, in run
      self.distinfo_dir)
    File "/usr/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 427, in egg2dist
      distribution=self.distribution)
    File "/usr/local/lib/python2.7/site-packages/wheel/metadata.py", line 130, in pkginfo_to_dict
      payload = payload.decode('utf-8')
    File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
      return codecs.utf_8_decode(input, errors, True)
  UnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 1757: invalid start byte
```

**Comment by b-mueller** [comment]
Ho @forgetso, Mythril only works with Python 3.5. Try [pyenv](https://github.com/pyenv/pyenv).

**Comment by forgetso** [comment]
Thanks, I got it up and running with a conda env 👍
