### ISSUE TITLE
No script named 'myth'

### ISSUE THREAD

**Issue by brucewayne1392** [b-mueller/mythril#21]
Hi! :)
I'm working on Ubuntu 17.10 amd64.
I tried to install mythril with pip3 install mythril but, at the end of the installation (without any errors), when i write "myth --init-db" nothing happen. So, I tried to install it with 

$ git clone https://github.com/b-mueller/mythril/
$ cd mythril
$ python3 setup.py install

Now, when I try to execute myth --init-db ( or any other kind of command starting with myth) , I got

Traceback (most recent call last):
  File "/usr/local/bin/myth", line 4, in <module>
    __import__('pkg_resources').run_script('mythril==0.7.7', 'myth')
  File "/home/pippo/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/pippo/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1509, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'myth'

Can you help me? I really need mythril...

**Comment by b-mueller** [comment]
As @step21 said this is likely an issue with your Python environment. 

> when i write "myth --init-db" nothing happen. 

Is `myth` installed at all? What result do you get from `which myth`?

**Comment by b-mueller** [comment]
Closing due to lack of activity.
