### ISSUE TITLE
start_addr = disassembly.instruction_list[state.pc]['address']- List index out of range

### ISSUE THREAD

**Issue by cptmurphy** [b-mueller/mythril#24]
**ENV specs:**
- Ubuntu 16.04 LTS
- Python 3.5.2 [GCC 5.4.0 20160609]
- Virtualenv 15.1.0

**Installation output:**
>Building wheels for collected packages: mythril, ZODB, z3-solver, zc.lockfile, zodbpickle
  Running setup.py bdist_wheel for mythril ... done
  Stored in directory: /home/user/.cache/pip/wheels/06/b1/2e/ea5e2a3adcd7a0f68e6cc2ebbb58b18274fa69d42723594253
  Running setup.py bdist_wheel for ZODB ... done
  Stored in directory: /home/user/.cache/pip/wheels/4e/68/8c/f3ced7e225af0e7cc316c7a0755ef4201ae4b769affd5201e3
  Running setup.py bdist_wheel for z3-solver ... done
  Stored in directory: /home/user/.cache/pip/wheels/43/c7/d7/f37a4aa4cd2d081bdc8712f38943a372cce36f1920bfbc5926
  Running setup.py bdist_wheel for zc.lockfile ... done
  Stored in directory: /home/user/.cache/pip/wheels/1b/e1/63/8f77ec76bd7500ea412506af130751c030c642556d106fb307
  Running setup.py bdist_wheel for zodbpickle ... done
  Stored in directory: /home/user/.cache/pip/wheels/bf/ac/c1/1053fb885519d41f368ea46917a90fff8d127abffd121a5f17
Successfully built mythril ZODB z3-solver zc.lockfile zodbpickle
Installing collected packages: zope.interface, persistent, BTrees, ZConfig, transaction, zc.lockfile, zodbpickle, ZODB, z3-solver, laser-ethereum, mythril
Successfully installed BTrees-4.4.1 ZConfig-3.2.0 ZODB-5.3.0 laser-ethereum-0.2.16 mythril-0.8.10 persistent-4.2.4.2 transaction-2.1.2 z3-solver-4.5.1.0.post2 zc.lockfile-1.2.1 zodbpickle-0.7.0 zope.interface-4.4.3

**PIP list output:**
> asn1crypto (0.23.0)
BTrees (4.4.1)
certifi (2017.11.5)
cffi (1.11.2)
chardet (3.0.4)
coincurve (6.0.0)
cytoolz (0.8.2)
decorator (4.1.2)
ethereum (2.1.2)
ethereum-abi-utils (0.4.4)
ethereum-keys (0.1.0a7)
ethereum-tester (0.1.0b2)
ethereum-utils (0.6.0)
future (0.16.0)
idna (2.6)
ipython (6.2.1)
ipython-genutils (0.2.0)
jedi (0.11.0)
laser-ethereum (0.2.16)
mythril (0.8.10)
parso (0.1.0)
pbkdf2 (1.3)
persistent (4.2.4.2)
pexpect (4.3.0)
pickleshare (0.7.4)
pip (9.0.1)
prompt-toolkit (1.0.15)
ptyprocess (0.5.2)
py-ecc (1.4.2)
pycparser (2.18)
pycryptodome (3.4.6)
pyethash (0.1.27)
Pygments (2.2.0)
pylru (1.0.9)
pysha3 (1.0.2)
PyYAML (3.12)
repoze.lru (0.7)
requests (2.18.4)
rlp (0.6.0)
scrypt (0.8.0)
semantic-version (2.6.0)
setuptools (36.7.2)
simplegeneric (0.8.1)
six (1.11.0)
toolz (0.8.2)
traitlets (4.3.2)
transaction (2.1.2)
urllib3 (1.22)
wcwidth (0.1.7)
web3 (3.16.2)
wheel (0.30.0)
z3-solver (4.5.1.0.post2)
zc.lockfile (1.2.1)
ZConfig (3.2.0)
ZODB (5.3.0)
zodbpickle (0.7.0)
zope.interface (4.4.3)

**Command:**
`$ myth -g ./graph.html -a 0x9a642d6b3368ddc662CA244bAdf32cDA716005BC`

**0x9a642d6b3368ddc662CA244bAdf32cDA716005BC** - Qtum Contract.

**Traceback:**
>Traceback (most recent call last):
  File "/home/user/.virtualenvs/web3py/bin/myth", line 218, in <module>
    states = StateSpace(contracts, simplified=True)
  File "/home/user/.virtualenvs/web3py/lib/python3.5/site-packages/mythril/analysis/symbolic.py", line 25, in __init__
    self.svm.sym_exec(contracts[0].address)
  File "/home/user/.virtualenvs/web3py/lib/python3.5/site-packages/laser/ethereum/svm.py", line 183, in sym_exec
    node = self._sym_exec(context, State())
  File "/home/user/.virtualenvs/web3py/lib/python3.5/site-packages/laser/ethereum/svm.py", line 196, in _sym_exec
    start_addr = disassembly.instruction_list[state.pc]['address']
IndexError: list index out of range

**Comment by cptmurphy** [comment]
https://github.com/b-mueller/mythril/issues/8
