### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by misterch0c** [b-mueller/mythril#25]
Hello, firstly thanks for this great tool!

I'm having some issues with it, not sure if it comes from my side or not. I can scan some contracts without any problem but for most I get this error:
```
[unkn0wn@archie mythril]$ myth -x -a  0x234c402dbbf436259117e85aca506a0638d7b318 -v1
INFO:root:SVM initialized with dynamic loader: None
Traceback (most recent call last):
  File "/usr/bin/myth", line 4, in <module>
    __import__('pkg_resources').run_script('mythril==0.8.14', 'myth')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1524, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python3.6/site-packages/mythril-0.8.14-py3.6.egg/EGG-INFO/scripts/myth", line 236, in <module>
    states = StateSpace(contracts, simplified=False)
  File "/usr/lib/python3.6/site-packages/mythril-0.8.14-py3.6.egg/mythril/analysis/symbolic.py", line 25, in __init__
    self.svm.sym_exec(contracts[0].address)
  File "/usr/lib/python3.6/site-packages/laser/ethereum/svm.py", line 183, in sym_exec
    node = self._sym_exec(context, State())
  File "/usr/lib/python3.6/site-packages/laser/ethereum/svm.py", line 196, in _sym_exec
    start_addr = disassembly.instruction_list[state.pc]['address']
IndexError: list index out of range
```
Here's another contract which gives the same error: 0x0422fc05fe2306e7acfb373d977ad9def3ec86d3
And here's one for which it works fine: 0xfb9e9d3cbb2156353d6cce3296c33a274f133f03

I'm running a Parity node and the host is Archlinux

Thank you

**Comment by b-mueller** [comment]
Hi @misterch0c,

Those seem to be invalid addresses, at least on the mainnet:

https://etherscan.io/address/0x0422fc05fe2306e7acfb373d977ad9def3ec86d3
https://etherscan.io/address/0x234c402dbbf436259117e85aca506a0638d7b318

The 'list index out of range' error happens because there's no instructions (i.e. the eth_getCode response was empty). I'll add some error handling there so to make it clear what's happening!

**Comment by b-mueller** [comment]
Assuming that the issue was an empty contract response, this is now handled in 0.8.19.
