### ISSUE TITLE
KeyError error when building callgraph for contracts with external calls

### ISSUE THREAD

**Issue by Raz0r** [b-mueller/mythril#38]
* 1
```
(venv3) ❯ ./myth -g "test.html" -l --infura-mainnet -a 0x49fddeae0b521dab8d0c4b77e7161094f971320d
Traceback (most recent call last):
  File "./myth", line 251, in <module>
    states = StateSpace(contracts, dynloader=DynLoader(eth), simplified=True)
  File "/home/raz0r/Projects/mythril/mythril/analysis/symbolic.py", line 25, in __init__
    self.svm.sym_exec(contracts[0].address)
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 186, in sym_exec
    node = self._sym_exec(context, State())
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 841, in _sym_exec
    new_node = self._sym_exec(context, new_state, depth=depth+1, constraints=new_constraints)
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 774, in _sym_exec
    new_node = self._sym_exec(context, new_state, depth=depth+1, constraints=constraints)
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 841, in _sym_exec
    new_node = self._sym_exec(context, new_state, depth=depth+1, constraints=new_constraints)
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 989, in _sym_exec
    new_node = self._sym_exec(callee_context, State(), depth=depth+1, constraints=constraints)
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 827, in _sym_exec
    if jump_addr not in self.addr_visited[context.module['address']]:
KeyError: '0x1d3b2638a7cc9f2cb3d298a3da7a90b67e5506ed'
```
* 2
```
venv3) ❯ ./myth -g "test2.html" -l --infura-mainnet -a 0xd780ae2bf04cd96e577d3d014762f831d97129d0
Traceback (most recent call last):
  File "./myth", line 251, in <module>
    states = StateSpace(contracts, dynloader=DynLoader(eth), simplified=True)
  File "/home/raz0r/Projects/mythril/mythril/analysis/symbolic.py", line 25, in __init__
    self.svm.sym_exec(contracts[0].address)
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 186, in sym_exec
    node = self._sym_exec(context, State())
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 864, in _sym_exec
    new_node = self._sym_exec(context, new_state, depth=depth, constraints=new_constraints)
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 864, in _sym_exec
    new_node = self._sym_exec(context, new_state, depth=depth, constraints=new_constraints)
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 864, in _sym_exec
    new_node = self._sym_exec(context, new_state, depth=depth, constraints=new_constraints)
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 864, in _sym_exec
    new_node = self._sym_exec(context, new_state, depth=depth, constraints=new_constraints)
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 864, in _sym_exec
    new_node = self._sym_exec(context, new_state, depth=depth, constraints=new_constraints)
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 864, in _sym_exec
    new_node = self._sym_exec(context, new_state, depth=depth, constraints=new_constraints)
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 864, in _sym_exec
    new_node = self._sym_exec(context, new_state, depth=depth, constraints=new_constraints)
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 864, in _sym_exec
    new_node = self._sym_exec(context, new_state, depth=depth, constraints=new_constraints)
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 864, in _sym_exec
    new_node = self._sym_exec(context, new_state, depth=depth, constraints=new_constraints)
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 864, in _sym_exec
    new_node = self._sym_exec(context, new_state, depth=depth, constraints=new_constraints)
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 864, in _sym_exec
    new_node = self._sym_exec(context, new_state, depth=depth, constraints=new_constraints)
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 864, in _sym_exec
    new_node = self._sym_exec(context, new_state, depth=depth, constraints=new_constraints)
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 841, in _sym_exec
    new_node = self._sym_exec(context, new_state, depth=depth+1, constraints=new_constraints)
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 841, in _sym_exec
    new_node = self._sym_exec(context, new_state, depth=depth+1, constraints=new_constraints)
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 774, in _sym_exec
    new_node = self._sym_exec(context, new_state, depth=depth+1, constraints=constraints)
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 774, in _sym_exec
    new_node = self._sym_exec(context, new_state, depth=depth+1, constraints=constraints)
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 841, in _sym_exec
    new_node = self._sym_exec(context, new_state, depth=depth+1, constraints=new_constraints)
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 841, in _sym_exec
    new_node = self._sym_exec(context, new_state, depth=depth+1, constraints=new_constraints)
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 841, in _sym_exec
    new_node = self._sym_exec(context, new_state, depth=depth+1, constraints=new_constraints)
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 989, in _sym_exec
    new_node = self._sym_exec(callee_context, State(), depth=depth+1, constraints=constraints)
  File "/home/raz0r/venv3/lib/python3.5/site-packages/laser/ethereum/svm.py", line 827, in _sym_exec
    if jump_addr not in self.addr_visited[context.module['address']]:
KeyError: '0x1d3b2638a7cc9f2cb3d298a3da7a90b67e5506ed'
```

**Comment by b-mueller** [comment]
Bug is fixed and tested with:

```
$ myth --infura-mainnet -l -g ~/Desktop/test.html -a 0x49fddeae0b521dab8d0c4b77e7161094f971320d --max-depth 8
$ myth --infura-mainnet -l -g ~/Desktop/test.html -a 0xd780ae2bf04cd96e577d3d014762f831d97129d0 --max-depth 8
```

The resulting graphs look pretty crazy though :)

**Comment by Raz0r** [comment]
Cool, thanks! Will check it out.
