### ISSUE TITLE
pip install fails on Ubuntu 16.04 x86_64

### ISSUE THREAD

**Issue by myhndl** [b-mueller/mythril#9]
```
$ pip install mythril
Collecting mythril
  Using cached mythril-0.4.4.tar.gz
Collecting ethereum>=2.0.4 (from mythril)
Collecting web3 (from mythril)
Collecting ZODB>=5.3.0 (from mythril)
Collecting graphviz>=0.8 (from mythril)
  Using cached graphviz-0.8.1-py2.py3-none-any.whl
Collecting z3-solver>=4.5 (from mythril)
  Using cached z3_solver-4.5.1.0.post2-py2-none-manylinux1_x86_64.whl
Collecting laser-ethereum (from mythril)
  Using cached laser_ethereum-0.1.2-py2.py3-none-any.whl
Collecting pbkdf2 (from ethereum>=2.0.4->mythril)
Collecting scrypt (from ethereum>=2.0.4->mythril)
Collecting PyYAML (from ethereum>=2.0.4->mythril)
Collecting repoze.lru (from ethereum>=2.0.4->mythril)
Collecting pysha3>=1.0.1 (from ethereum>=2.0.4->mythril)
  Using cached pysha3-1.0.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting coincurve>=5.0.1 (from ethereum>=2.0.4->mythril)
  Using cached coincurve-6.0.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pycryptodome==3.4.6 (from ethereum>=2.0.4->mythril)
Collecting py-ecc (from ethereum>=2.0.4->mythril)
Collecting pyethash (from ethereum>=2.0.4->mythril)
Collecting rlp>=0.4.7 (from ethereum>=2.0.4->mythril)
Collecting ethereum-tester~=0.1.0b2 (from web3->mythril)
Collecting pylru>=1.0.9 (from web3->mythril)
Collecting ethereum-utils>=0.5.0 (from web3->mythril)
Collecting toolz>=0.8.2 (from web3->mythril)
Collecting ethereum-abi-utils>=0.4.3 (from web3->mythril)
Collecting cytoolz>=0.8.2 (from web3->mythril)
Collecting requests>=2.12.4 (from web3->mythril)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting zope.interface (from ZODB>=5.3.0->mythril)
  Using cached zope.interface-4.4.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting zodbpickle>=0.6.0 (from ZODB>=5.3.0->mythril)
Collecting six (from ZODB>=5.3.0->mythril)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting persistent>=4.2.0 (from ZODB>=5.3.0->mythril)
  Using cached persistent-4.2.4.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting BTrees>=4.2.0 (from ZODB>=5.3.0->mythril)
  Using cached BTrees-4.4.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting transaction>=2.0.3 (from ZODB>=5.3.0->mythril)
  Using cached transaction-2.1.2-py2.py3-none-any.whl
Collecting zc.lockfile (from ZODB>=5.3.0->mythril)
Collecting ZConfig (from ZODB>=5.3.0->mythril)
  Using cached ZConfig-3.2.0-py2.py3-none-any.whl
Collecting cffi>=1.3.0 (from coincurve>=5.0.1->ethereum>=2.0.4->mythril)
  Using cached cffi-1.11.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting asn1crypto (from coincurve>=5.0.1->ethereum>=2.0.4->mythril)
  Using cached asn1crypto-0.23.0-py2.py3-none-any.whl
Collecting ethereum-keys>=0.1.0-alpha.7 (from ethereum-tester~=0.1.0b2->web3->mythril)
Collecting semantic-version>=2.6.0 (from ethereum-tester~=0.1.0b2->web3->mythril)
Collecting urllib3<1.23,>=1.21.1 (from requests>=2.12.4->web3->mythril)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests>=2.12.4->web3->mythril)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.12.4->web3->mythril)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.12.4->web3->mythril)
  Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
Collecting setuptools (from zope.interface->ZODB>=5.3.0->mythril)
  Using cached setuptools-36.6.0-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.3.0->coincurve>=5.0.1->ethereum>=2.0.4->mythril)
Building wheels for collected packages: mythril
  Running setup.py bdist_wheel for mythril ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-u5aVKD/mythril/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpjIDTZEpip-wheel- --python-tag cp27:
  /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/mythril
  copying mythril/__init__.py -> build/lib.linux-x86_64-2.7/mythril
  creating build/lib.linux-x86_64-2.7/laser
  copying laser/__init__.py -> build/lib.linux-x86_64-2.7/laser
  creating build/lib.linux-x86_64-2.7/mythril/ether
  copying mythril/ether/asm.py -> build/lib.linux-x86_64-2.7/mythril/ether
  copying mythril/ether/__init__.py -> build/lib.linux-x86_64-2.7/mythril/ether
  copying mythril/ether/ethcontract.py -> build/lib.linux-x86_64-2.7/mythril/ether
  copying mythril/ether/contractstorage.py -> build/lib.linux-x86_64-2.7/mythril/ether
  copying mythril/ether/util.py -> build/lib.linux-x86_64-2.7/mythril/ether
  copying mythril/ether/evm.py -> build/lib.linux-x86_64-2.7/mythril/ether
  creating build/lib.linux-x86_64-2.7/mythril/ipc
  copying mythril/ipc/utils.py -> build/lib.linux-x86_64-2.7/mythril/ipc
  copying mythril/ipc/exceptions.py -> build/lib.linux-x86_64-2.7/mythril/ipc
  copying mythril/ipc/__init__.py -> build/lib.linux-x86_64-2.7/mythril/ipc
  copying mythril/ipc/constants.py -> build/lib.linux-x86_64-2.7/mythril/ipc
  copying mythril/ipc/client.py -> build/lib.linux-x86_64-2.7/mythril/ipc
  creating build/lib.linux-x86_64-2.7/mythril/disassembler
  copying mythril/disassembler/callgraph.py -> build/lib.linux-x86_64-2.7/mythril/disassembler
  copying mythril/disassembler/__init__.py -> build/lib.linux-x86_64-2.7/mythril/disassembler
  copying mythril/disassembler/disassembly.py -> build/lib.linux-x86_64-2.7/mythril/disassembler
  creating build/lib.linux-x86_64-2.7/mythril/rpc
  copying mythril/rpc/utils.py -> build/lib.linux-x86_64-2.7/mythril/rpc
  copying mythril/rpc/exceptions.py -> build/lib.linux-x86_64-2.7/mythril/rpc
  copying mythril/rpc/__init__.py -> build/lib.linux-x86_64-2.7/mythril/rpc
  copying mythril/rpc/constants.py -> build/lib.linux-x86_64-2.7/mythril/rpc
  copying mythril/rpc/client.py -> build/lib.linux-x86_64-2.7/mythril/rpc
  creating build/lib.linux-x86_64-2.7/laser/ethereum
  copying laser/ethereum/utils.py -> build/lib.linux-x86_64-2.7/laser/ethereum
  copying laser/ethereum/laserfree.py -> build/lib.linux-x86_64-2.7/laser/ethereum
  copying laser/ethereum/__init__.py -> build/lib.linux-x86_64-2.7/laser/ethereum
  copying laser/ethereum/svm.py -> build/lib.linux-x86_64-2.7/laser/ethereum
  copying laser/ethereum/cfg.py -> build/lib.linux-x86_64-2.7/laser/ethereum
  creating build/lib.linux-x86_64-2.7/laser/ethereum/modules
  copying laser/ethereum/modules/unchecked_send.py -> build/lib.linux-x86_64-2.7/laser/ethereum/modules
  copying laser/ethereum/modules/__init__.py -> build/lib.linux-x86_64-2.7/laser/ethereum/modules
  running egg_info
  writing requirements to mythril.egg-info/requires.txt
  writing mythril.egg-info/PKG-INFO
  writing top-level names to mythril.egg-info/top_level.txt
  writing dependency_links to mythril.egg-info/dependency_links.txt
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'mythril.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'mythril.egg-info/SOURCES.txt'
  copying mythril/disassembler/signatures.json -> build/lib.linux-x86_64-2.7/mythril/disassembler
  running build_scripts
  creating build/scripts-2.7
  copying and adjusting myth -> build/scripts-2.7
  changing mode of build/scripts-2.7/myth from 664 to 775
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/mythril
  creating build/bdist.linux-x86_64/wheel/mythril/ether
  copying build/lib.linux-x86_64-2.7/mythril/ether/asm.py -> build/bdist.linux-x86_64/wheel/mythril/ether
  copying build/lib.linux-x86_64-2.7/mythril/ether/__init__.py -> build/bdist.linux-x86_64/wheel/mythril/ether
  copying build/lib.linux-x86_64-2.7/mythril/ether/ethcontract.py -> build/bdist.linux-x86_64/wheel/mythril/ether
  copying build/lib.linux-x86_64-2.7/mythril/ether/contractstorage.py -> build/bdist.linux-x86_64/wheel/mythril/ether
  copying build/lib.linux-x86_64-2.7/mythril/ether/util.py -> build/bdist.linux-x86_64/wheel/mythril/ether
  copying build/lib.linux-x86_64-2.7/mythril/ether/evm.py -> build/bdist.linux-x86_64/wheel/mythril/ether
  creating build/bdist.linux-x86_64/wheel/mythril/ipc
  copying build/lib.linux-x86_64-2.7/mythril/ipc/utils.py -> build/bdist.linux-x86_64/wheel/mythril/ipc
  copying build/lib.linux-x86_64-2.7/mythril/ipc/exceptions.py -> build/bdist.linux-x86_64/wheel/mythril/ipc
  copying build/lib.linux-x86_64-2.7/mythril/ipc/__init__.py -> build/bdist.linux-x86_64/wheel/mythril/ipc
  copying build/lib.linux-x86_64-2.7/mythril/ipc/constants.py -> build/bdist.linux-x86_64/wheel/mythril/ipc
  copying build/lib.linux-x86_64-2.7/mythril/ipc/client.py -> build/bdist.linux-x86_64/wheel/mythril/ipc
  copying build/lib.linux-x86_64-2.7/mythril/__init__.py -> build/bdist.linux-x86_64/wheel/mythril
  creating build/bdist.linux-x86_64/wheel/mythril/disassembler
  copying build/lib.linux-x86_64-2.7/mythril/disassembler/callgraph.py -> build/bdist.linux-x86_64/wheel/mythril/disassembler
  copying build/lib.linux-x86_64-2.7/mythril/disassembler/__init__.py -> build/bdist.linux-x86_64/wheel/mythril/disassembler
  copying build/lib.linux-x86_64-2.7/mythril/disassembler/disassembly.py -> build/bdist.linux-x86_64/wheel/mythril/disassembler
  copying build/lib.linux-x86_64-2.7/mythril/disassembler/signatures.json -> build/bdist.linux-x86_64/wheel/mythril/disassembler
  creating build/bdist.linux-x86_64/wheel/mythril/rpc
  copying build/lib.linux-x86_64-2.7/mythril/rpc/utils.py -> build/bdist.linux-x86_64/wheel/mythril/rpc
  copying build/lib.linux-x86_64-2.7/mythril/rpc/exceptions.py -> build/bdist.linux-x86_64/wheel/mythril/rpc
  copying build/lib.linux-x86_64-2.7/mythril/rpc/__init__.py -> build/bdist.linux-x86_64/wheel/mythril/rpc
  copying build/lib.linux-x86_64-2.7/mythril/rpc/constants.py -> build/bdist.linux-x86_64/wheel/mythril/rpc
  copying build/lib.linux-x86_64-2.7/mythril/rpc/client.py -> build/bdist.linux-x86_64/wheel/mythril/rpc
  creating build/bdist.linux-x86_64/wheel/laser
  copying build/lib.linux-x86_64-2.7/laser/__init__.py -> build/bdist.linux-x86_64/wheel/laser
  creating build/bdist.linux-x86_64/wheel/laser/ethereum
  copying build/lib.linux-x86_64-2.7/laser/ethereum/utils.py -> build/bdist.linux-x86_64/wheel/laser/ethereum
  copying build/lib.linux-x86_64-2.7/laser/ethereum/laserfree.py -> build/bdist.linux-x86_64/wheel/laser/ethereum
  creating build/bdist.linux-x86_64/wheel/laser/ethereum/modules
  copying build/lib.linux-x86_64-2.7/laser/ethereum/modules/unchecked_send.py -> build/bdist.linux-x86_64/wheel/laser/ethereum/modules
  copying build/lib.linux-x86_64-2.7/laser/ethereum/modules/__init__.py -> build/bdist.linux-x86_64/wheel/laser/ethereum/modules
  copying build/lib.linux-x86_64-2.7/laser/ethereum/__init__.py -> build/bdist.linux-x86_64/wheel/laser/ethereum
  copying build/lib.linux-x86_64-2.7/laser/ethereum/svm.py -> build/bdist.linux-x86_64/wheel/laser/ethereum
  copying build/lib.linux-x86_64-2.7/laser/ethereum/cfg.py -> build/bdist.linux-x86_64/wheel/laser/ethereum
  running install_egg_info
  Copying mythril.egg-info to build/bdist.linux-x86_64/wheel/mythril-0.4.4.egg-info
  running install_scripts
  creating build/bdist.linux-x86_64/wheel/mythril-0.4.4.data
  creating build/bdist.linux-x86_64/wheel/mythril-0.4.4.data/scripts
  copying build/scripts-2.7/myth -> build/bdist.linux-x86_64/wheel/mythril-0.4.4.data/scripts
  changing mode of build/bdist.linux-x86_64/wheel/mythril-0.4.4.data/scripts/myth to 775
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-u5aVKD/mythril/setup.py", line 270, in <module>
      scripts=['myth']
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 232, in run
      self.distinfo_dir)
    File "/usr/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 399, in egg2dist
      distribution=self.distribution)
    File "/usr/lib/python2.7/dist-packages/wheel/metadata.py", line 129, in pkginfo_to_dict
      payload = payload.decode('utf-8')
    File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
      return codecs.utf_8_decode(input, errors, True)
  UnicodeDecodeError: 'utf8' codec can't decode bytes in position 3563-3564: invalid continuation byte
  
  ----------------------------------------
  Failed building wheel for mythril
  Running setup.py clean for mythril
Failed to build mythril
Installing collected packages: pbkdf2, scrypt, PyYAML, repoze.lru, pysha3, pycparser, cffi, asn1crypto, coincurve, pycryptodome, py-ecc, pyethash, rlp, ethereum, toolz, cytoolz, ethereum-utils, ethereum-keys, semantic-version, ethereum-tester, pylru, ethereum-abi-utils, urllib3, idna, chardet, certifi, requests, web3, setuptools, zope.interface, zodbpickle, six, persistent, BTrees, transaction, zc.lockfile, ZConfig, ZODB, graphviz, z3-solver, laser-ethereum, mythril
Segmentation fault
```

**Comment by myhndl** [comment]
Reading through `setup.py`, it appears as though Python >= 3.5 is intended as a requirement.

Given Python 2's default status in a lot of distros, pip's apparent inability to properly handle this requirement, it may make sense to make this requirement explicit in documentation or bail if python2 is being used?

The following worked:
```
$ sudo apt install python3-pip
$ pip3 install mythril
$ myth
```

**Comment by pirapira** [comment]
@myhndl that worked after I added `~/.local/bin` to PATH.

**Comment by b-mueller** [comment]
Hi @myhndl, setup.py contains the line:

```
python_requires='>=3.5',
```

I was assuming that this would prevent installation in a Python 2 environment? 
Also the segmentation fault you are getting is pretty weird :)

**Comment by myhndl** [comment]
@b-mueller yeah that was the line in `setup.py` that I referring to. Unfortunately, Ubuntu 16.04 is going to ignore that line.

Ubuntu 16.04's PIP package is 8.1.1 (https://packages.ubuntu.com/xenial/python/python-pip), but support for `python_requires` wasn't added until PIP 9 (https://media.readthedocs.org/pdf/python-packaging-user-guide/latest/python-packaging-user-guide.pdf)

I'm not sure offhand what the least-hacky option is here, maybe just document that Python / PIP 3 is required? Seems like Ubuntu 16.04 is a bit behind the times.

And yes, segmentation faults are always interesting, maybe I'll run that down when I get some time :)

**Comment by step21** [comment]
I am also using this on Ubuntu 16.04 but I guess I got quite used to things not always being clear between Python 2 and 3. Then, `pip / pip3` depending on what is needed.

**Comment by b-mueller** [comment]
I documented this in the README.
